// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Akgod
{
    public int IdAkGod { get; set; }

    public string Razdoblje { get; set; }

    public virtual ICollection<Raspored> Rasporeds { get; set; } = new List<Raspored>();

    public virtual ICollection<Vijeće> Vijećes { get; set; } = new List<Vijeće>();
}