// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Dvorana
{
    public string OznDvorana { get; set; }

    public int IdDvorana { get; set; }

    public int Kapacitet { get; set; }

    public virtual ICollection<Raspored> Rasporeds { get; set; } = new List<Raspored>();

    public virtual ICollection<Sjednica> Sjednicas { get; set; } = new List<Sjednica>();
}