// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Fakultetsko
{
    public int IdVijeca { get; set; }

    public virtual Vijeće IdVijecaNavigation { get; set; }

    public virtual ICollection<OdlukeFv> IdOdlukes { get; set; } = new List<OdlukeFv>();
}