// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class FinModul
{
    public string VrstaModula { get; set; }

    public int IdFinModul { get; set; }

    public virtual ICollection<Osoba> Oibs { get; set; } = new List<Osoba>();
}