// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class NatjecajZaUpi
{
    public int IdNatjecanja { get; set; }

    public DateOnly DatumOtvaranja { get; set; }

    public int BrojMjesta { get; set; }

    public int IdStatus { get; set; }

    public virtual StatusNatjecaja IdStatusNavigation { get; set; }

    public virtual ICollection<Prijava> IdUpisas { get; set; } = new List<Prijava>();
}