// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Osoba
{
    public string Ime { get; set; }

    public string Prezime { get; set; }

    public DateOnly DatumRodenja { get; set; }

    public string Email { get; set; }

    public string BrojMobitela { get; set; }

    public string Iban { get; set; }

    public string Oib { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<Transakcija> Transakcijas { get; set; } = new List<Transakcija>();

    public virtual Zaposlenik Zaposlenik { get; set; }

    public virtual ICollection<FinModul> IdFinModuls { get; set; } = new List<FinModul>();
}