// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Povjerentsvo
{
    public int IdVijeca { get; set; }

    public int IdVijecaStrucno { get; set; }

    public virtual Vijeće IdVijecaNavigation { get; set; }

    public virtual Strucno IdVijecaStrucnoNavigation { get; set; }

    public virtual ICollection<ZavrsniRad> ZavrsniRads { get; set; } = new List<ZavrsniRad>();
}