// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class Predmet
{
	[Display(Name = "ID predmeta", Prompt = "Unesite ID predmeta")]
	public int SifPredmet { get; set; }

	[Display(Name = "Naziv", Prompt = "Unesite naziv")]
	public string Naziv { get; set; }

	[Display(Name = "Plan", Prompt = "Unesite plan predmeta")]
	public string PlanProgram { get; set; }

	[Display(Name = "Program", Prompt = "Unesite program predmeta")]
	public string Program { get; set; }

	[Display(Name = "Izboran predmet", Prompt = "Odaberite je li predmet izboran")]
	public int JelIzboran { get; set; }

	[Display(Name = "ECTS", Prompt = "Unesite broj ECTS-a")]
	public double Ects { get; set; }

    public virtual ICollection<PredUlogaZap> PredUlogaZaps { get; set; } = new List<PredUlogaZap>();

    public virtual ICollection<Predavanje> Predavanjes { get; set; } = new List<Predavanje>();

    public virtual ICollection<Prijava> IdUpisas { get; set; } = new List<Prijava>();
}