// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class PredUlogaZap
{
    public int IdPredUlogaZap { get; set; }

    public int SifPredmet { get; set; }

    public string Oib { get; set; }

    public int UlogaId { get; set; }

    public virtual Zaposlenik OibNavigation { get; set; }

    public virtual Predmet SifPredmetNavigation { get; set; }

    public virtual UlogaNaPred Uloga { get; set; }
}