// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Predmet
{
    public int SifPredmet { get; set; }

    public string Naziv { get; set; }

    public string PlanProgram { get; set; }

    public string Program { get; set; }

    public int JelIzboran { get; set; }

    public double Ects { get; set; }

    public virtual ICollection<PredUlogaZap> PredUlogaZaps { get; set; } = new List<PredUlogaZap>();

    public virtual ICollection<Predavanje> Predavanjes { get; set; } = new List<Predavanje>();

    public virtual ICollection<Prijava> IdUpisas { get; set; } = new List<Prijava>();
}