// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Predavanje
{
    public DateTime VrijemePocetka { get; set; }

    public DateTime VrijemeZavrsetka { get; set; }

    public int IdPredavanja { get; set; }

    public int IdRaspored { get; set; }

    public int SifPredmet { get; set; }

    public virtual Raspored IdRasporedNavigation { get; set; }

    public virtual Predmet SifPredmetNavigation { get; set; }

    public virtual ICollection<Zaposlenik> Oibs { get; set; } = new List<Zaposlenik>();
}