// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using RPPP_WebApp.Models.Validation;

namespace RPPP_WebApp.Models;

public partial class Predavanje
{
	[Display(Name = "Vrijeme početka", Prompt = "Odaberite vrijeme početka")]
    public DateTime VrijemePocetka { get; set; }

	[Display(Name = "Vrijeme završetka", Prompt = "Odaberite vrijeme završetka")]
    [ValidnoVrijemeZavrsetka(ErrorMessage = "Vrijeme završetka mora biti nakon vremena početka.")]
    public DateTime VrijemeZavrsetka { get; set; }

	[Display(Name = "ID predavanja", Prompt = "Unesite ID predavanja")]
	public int IdPredavanja { get; set; }

	[Display(Name = "Raspored", Prompt = "Odaberite raspored")]
	public int IdRaspored { get; set; }

	[Display(Name = "Predmet", Prompt = "Odaberite predmet")]
	public int SifPredmet { get; set; }

    public virtual Raspored IdRasporedNavigation { get; set; }

    public virtual Predmet SifPredmetNavigation { get; set; }

    public virtual ICollection<Zaposlenik> Oibs { get; set; } = new List<Zaposlenik>();
}