// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Prijava
{
    public string StatusUpisa { get; set; }

    public int BrUpisa { get; set; }

    public DateOnly RokTrajanja { get; set; }

    public DateOnly DatumUpisa { get; set; }

    public int IdUpisa { get; set; }

    public int IdPrijave { get; set; }

    public virtual StatusPrijave IdPrijaveNavigation { get; set; }

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<NatjecajZaUpi> IdNatjecanjas { get; set; } = new List<NatjecajZaUpi>();

    public virtual ICollection<Predmet> SifPredmets { get; set; } = new List<Predmet>();
}