// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Raspored
{
    public int IdRaspored { get; set; }

    public string Opis { get; set; }

    public int IdAkGod { get; set; }

    public int IdDvorana { get; set; }

    public virtual Akgod IdAkGodNavigation { get; set; }

    public virtual Dvorana IdDvoranaNavigation { get; set; }

    public virtual ICollection<Predavanje> Predavanjes { get; set; } = new List<Predavanje>();
}