// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class StatusPrijave
{
    public int IdPrijave { get; set; }

    [Required(ErrorMessage = "Naziv statusa natjecanja je obavezan.")]
    [StringLength(40, ErrorMessage = "Naziv statusa natjecanja ne može imati više od 40 znakova.")]
    public string StatusPrijave1 { get; set; }

    public virtual ICollection<Prijava> Prijavas { get; set; } = new List<Prijava>();
}