// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class StatusNatjecaja
{
    public int IdStatus { get; set; }

    public string StatusNatjecanja { get; set; }

    public virtual ICollection<NatjecajZaUpi> NatjecajZaUpis { get; set; } = new List<NatjecajZaUpi>();
}