// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class StatusPrijave
{
    public int IdPrijave { get; set; }

    public string StatusPrijave1 { get; set; }

    public virtual ICollection<Prijava> Prijavas { get; set; } = new List<Prijava>();
}