// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Strucno
{
    public int IdVijeca { get; set; }

    public virtual Vijeće IdVijecaNavigation { get; set; }

    public virtual ICollection<Povjerentsvo> Povjerentsvos { get; set; } = new List<Povjerentsvo>();
}