// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Student
{
    public string Jmbag { get; set; }

    public string Oib { get; set; }

    public int IdUpisa { get; set; }

    public string OibMentora { get; set; }

    public virtual Prijava IdUpisaNavigation { get; set; }

    public virtual Zaposlenik OibMentoraNavigation { get; set; }

    public virtual Osoba OibNavigation { get; set; }

    public virtual ICollection<ZavrsniRad> ZavrsniRads { get; set; } = new List<ZavrsniRad>();
}