// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Transakcija
{
    public DateTime VrijemeTranskacije { get; set; }

    public double Iznos { get; set; }

    public int BrRata { get; set; }

    public int IdTransakcije { get; set; }

    public string RacunPosiljatelja { get; set; }

    public string RacunPrimatelja { get; set; }

    public string Oib { get; set; }

    public int IdStatus { get; set; }

    public virtual StatusTran IdStatusNavigation { get; set; }

    public virtual Osoba OibNavigation { get; set; }
}