// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class UlogaNaPred
{
    public int UlogaId { get; set; }

    public string UlogaNaziv { get; set; }

    public virtual ICollection<PredUlogaZap> PredUlogaZaps { get; set; } = new List<PredUlogaZap>();
}