// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Vijeće
{
    public int IdVijeca { get; set; }

    public int IdAkGod { get; set; }

    public virtual Fakultetsko Fakultetsko { get; set; }

    public virtual Akgod IdAkGodNavigation { get; set; }

    public virtual Povjerentsvo Povjerentsvo { get; set; }

    public virtual ICollection<Sjednica> Sjednicas { get; set; } = new List<Sjednica>();

    public virtual Strucno Strucno { get; set; }

    public virtual ICollection<VijeceUlogaZap> VijeceUlogaZaps { get; set; } = new List<VijeceUlogaZap>();
}