// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RPPP_WebApp.Models;

public partial class VrstaOdluke
{

    public int IdVrstaOdluke { get; set; }
    [Required(ErrorMessage = "Potrebno je unijeti vrstu odluke.")]
    [Display(Name = "Vrsta odluke")]
    public string VrstaOdluke1 { get; set; }

    public virtual ICollection<OdlukeFv> OdlukeFvs { get; set; } = new List<OdlukeFv>();
}