// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class VrstaOdluke
{
    public int IdVrstaOdluke { get; set; }

    public string VrstaOdluke1 { get; set; }

    public virtual ICollection<OdlukeFv> OdlukeFvs { get; set; } = new List<OdlukeFv>();
}