// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RPPP_WebApp.Models;

public partial class Zaposlenik
{
    public int IdClan { get; set; }

    public string Oib { get; set; }

    public virtual Osoba OibNavigation { get; set; }

    public virtual ICollection<PredUlogaZap> PredUlogaZaps { get; set; } = new List<PredUlogaZap>();

    public virtual ICollection<Student> Students { get; set; } = new List<Student>();

    public virtual ICollection<VijeceUlogaZap> VijeceUlogaZaps { get; set; } = new List<VijeceUlogaZap>();

    public virtual ICollection<Predavanje> IdPredavanjas { get; set; } = new List<Predavanje>();
}